[package]
name = "utils"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"

[dependencies]
rustls = "0.23"
env_logger = "0.11.8"
base64 = "0.22"
tokio-stream = "0.1.17"
futures-util = { version = "0.3.30" }
pretty_env_logger = "0.5.0"
borsh = "1.5.5"
spl-token = { version = "8.0.0", features = ["no-entrypoint"] }
solana-system-interface = "1.0.0"
serde = "1.0.219"
async-trait = "0.1.88"
rand = "0.9.1"
reqwest = "0.12.22"
bincode = "1.3.3"
teloxide = { version = "0.17.0", features = ["macros"] }
jito-sdk-rust    = "0.2.1"
serde_json = "1.0.145"
solana-sdk = "2.2.2"
tokio = "1.48.0"
solana-client = "2.2.2"
chrono = "0.4.42"
spl-associated-token-account = { version = "7.0.0", features = [
    "no-entrypoint",
] }
log = "0.4.28"
anyhow = "1.0.100"
grpc-client = { git = "https://github.com/miaomiaowu0428/grpc-client.git" }
ta = "0.5.0"
